version: 0.1

phases:
  install:
    commands:
      - export GOPATH=/var/projects
      - export GOROOT=/usr/lib/golang
      - export PATH=$PATH:$GOPATH/bin
      - export PATH=$PATH:$GOROOT/bin
  build:
    commands:
      - go build -o gotham
artifacts:
  files:
    - gotham
    - buildspec.yml
    - appspec.yml
    - .env
    - codedeploy/*
    - '**/*'